###############################################################################
# StaticStats — Main configuration
#
# Lightweight, fast, and easy-to-configure statistics GUI & commands.
# - Use /stats to open the GUI or /stats reload to apply changes made to
#   config.yml and messages.yml without restarting the server.
# - The GUI is fully configurable under the 'stats-gui' section.
# - Permissions are configurable under 'permissions' or 'commands' sections.
#
# THANK YOU NOTE:
# Thank you for using StaticStats! Your support helps keep this plugin
# lightweight and maintained. If you want Vault or persistence features, add
# them via the plugin options (or request via the dev).
#
# Quick tips:
# - Edit messages in messages.yml (recommended) instead of directly changing
#   text used by the plugin in code.
# - After editing config.yml or messages.yml run: /stats reload
###############################################################################

permissions:
  stats:
    permission: "stats.use"
    reload-permission: "stats.reload"
  setstats:
    permission: "stats.set"
    others-permission: "stats.set.others"

stats-gui:
  title: "ѕᴛᴀᴛѕ"
  size: 27
  items:
    fill:
      material: GRAY_STAINED_GLASS_PANE
      name: "&r"
      lore: []

    head:
      slot: 4
      material: PLAYER_HEAD
      name: "&#8094fb&lPROFILE"
      lore:
        - "&fName: &#8094fb%player_name%"

    rank:
      slot: 11
      material: BOOK
      name: "&#09ABF6&lRANK"
      lore:
        - "&#09ABF6• &f%player_name%'s rank: %luckperms_prefix%"

    kills:
      slot: 12
      material: END_CRYSTAL
      name: "&c&lKILLS"
      lore:
        - "&c• &f%player_name%'s Kills: %statistic_player_kills%"

    deaths:
      slot: 13
      material: SKELETON_SKULL
      name: "&#666666&lDEATHS"
      lore:
        - "&#666666• &f%player_name%'s Deaths: %statistic_deaths%"

    balance:
      slot: 14
      material: PAPER
      name: "&#05ff00&lBALANCE"
      lore:
        - "&#05ff00• &f%vault_eco_balance_formatted%$"

    playtime:
      slot: 15
      material: CLOCK
      name: "&7&lPLAYTIME"
      lore:
        - "&7• &f%statistic_time_played:days%d %statistic_time_played:hours%h %statistic_time_played:minutes%m"