name: StaticStats
version: '${version}'
main: org.staticstudios.StaticStats
api-version: '1.21'
authors: [ StaticStudios ]
softdepend: [PlaceholderAPI]
description: "StaticStats — Lightweight, high-performance player statistics plugin (GUI + commands). Minimal footprint, PlaceholderAPI compatible."
commands:
  stats:
    description: "Open the stats GUI or reload configuration"
    usage: "/stats [player|reload]"

  setstats:
    description: "Set player statistics"
    usage: "/setstats <player> <stat> <value>"
